#!/bin/bash

# Update the package list
sudo apt-get update

# Install Apache and automatically answer "yes" to prompts
sudo apt-get install -y apache2

# Start the Apache service
sudo systemctl start apache2

# Enable Apache to start on boot
sudo systemctl enable apache2

# yum install -y httpd

